// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/game-day-post/GameDay.tsx": () => import("../components/mockups/game-day-post/GameDay.tsx"),
  "./components/mockups/schedule-post/FeaturesPost.tsx": () => import("../components/mockups/schedule-post/FeaturesPost.tsx"),
  "./components/mockups/schedule-post/SchedulePost.tsx": () => import("../components/mockups/schedule-post/SchedulePost.tsx"),
  "./components/mockups/schedule-post/Spotlight.tsx": () => import("../components/mockups/schedule-post/Spotlight.tsx"),
  "./components/mockups/schedule-post/TicketStrip.tsx": () => import("../components/mockups/schedule-post/TicketStrip.tsx"),
  "./components/mockups/schedule-post/TypePoster.tsx": () => import("../components/mockups/schedule-post/TypePoster.tsx")
};
